### ISSUE TITLE
config.ini - how to camera configuration

### ISSUE THREAD

**Issue by Eso2000** [markoelez/minislam#1]
Hi, 
how do you determine the camera confiuration in the config.ini file?
Any ideas how to do it with own mp4 file?
thanks!

**Comment by markoelez** [comment]
hey, I'll get back to you in a day or so, planning to refactor this

**Comment by markoelez** [comment]
updated the readme

you can use a custom mp4 file or a directory of image sequences, just add the associated metadata to `config.yaml` and specify the dataset name as a CLI argument
